version: '2'

services:
  angularapp: 
    build: web_app/ceiba-eafit
    ports:
    - "80:80"
    depends_on:
    - express

  express:
    container_name: express 
    build: server
    ports:
    - "3000:3000"
    depends_on:
    - database

  database:
    container_name: database 
    image: mongo
    volumes:
    - ./data:/data/db
    ports:
    - "27017:27017"