FROM node:6
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY package.json /usr/src/app
RUN npm cache clean
RUN npm install
RUN npm install -g @angular/cli
copy . /usr/src/app
EXPOSE 4200
CMD ["ng","serve"]